
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - fipeapi-network

  kafka:
    image: wurstmeister/kafka
    environment:
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_LISTENERS=${KAFKA_LISTENERS}
      - KAFKA_LISTENER_SECURITY_PROTOCOL=${KAFKA_LISTENER_SECURITY_PROTOCOL}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_LISTENER_NAME=${KAFKA_LISTENER_NAME}
      - KAFKA_LISTENER_PORT=${KAFKA_LISTENER_PORT}
      - KAFKA_LISTENER_HOSTNAME=${KAFKA_LISTENER_HOSTNAME}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_LISTENER_OUTSIDE_PORT=${KAFKA_LISTENER_OUTSIDE_PORT}
      - KAFKA_INTER_BROKER_LISTENER_NAME=${KAFKA_INTER_BROKER_LISTENER_NAME}
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

networks:
  fipeapi-network:
    driver: bridge
